version: "3"
services:
  library:
    image: postgres:14.5
    environment:
      POSTGRES_USER: "KULIKOV_204"
      POSTGRES_PASSWORD: "KULIKOV_204"
      POSTGRES_DB: "KULIKOV_204"
      PGDATA: "/var/lib/postgresql/data/library"
    ports:
      - "5430:5432"
    volumes:
      - ./docker/db/config/library.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/db/data/library:/var/lib/postgresql/data/library
  stations:
    image: postgres:14.5
    environment:
      POSTGRES_USER: "KULIKOV_204"
      POSTGRES_PASSWORD: "KULIKOV_204"
      POSTGRES_DB: "KULIKOV_204"
      PGDATA: "/var/lib/postgresql/data/stations"
    ports:
      - "5431:5432"
    volumes:
      - ./docker/db/config/stations.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/db/data/stations:/var/lib/postgresql/data/stations
  hospital:
    image: postgres:14.5
    environment:
      POSTGRES_USER: "KULIKOV_204"
      POSTGRES_PASSWORD: "KULIKOV_204"
      POSTGRES_DB: "KULIKOV_204"
      PGDATA: "/var/lib/postgresql/data/hospital"
    ports:
      - "5433:5432"
    volumes:
      - ./docker/db/config/hospital.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/db/data/hospital:/var/lib/postgresql/data/hospital
